### ISSUE TITLE
Better formatting for news entries

### ISSUE THREAD

**Issue by Tschonti** [kir-dev/schbody#36]
maybe markdown support?

or at least set the white-space rule to pre- something so newLines will be kept

**Comment by mozsarmate** [comment]
what kind of entries is this issue about?

**Comment by Tschonti** [comment]
news like these

![image](https://github.com/user-attachments/assets/df810eb0-8244-47fa-889d-067629fd4910)

**Comment by mozsarmate** [comment]
Nice! Thanks for clarifying, will do it
