### ISSUE TITLE
fix: DELETE periods throws 404 even if the entity exists

### ISSUE THREAD

**Issue by mozsarmate** [kir-dev/schbody#72]

**Comment by Tschonti** [comment]
I couldn't reproduce this. But sometimes the deleted period doesn't disappear from the period list until the page is refreshed

**Comment by mozsarmate** [comment]
I get a 404 each time if the period has at least one applicaiton assigned to it.
I succed to delete the period after i delete all the applications assigned manually

**Comment by mozsarmate** [comment]
maybe we should implement a delete applicaiton button for the admins?? @FearsomeRover

**Comment by Tschonti** [comment]
or you need to set the onDelete to cascade on the applicationPeriod entity so deleting it will delete all the related applications as well
