### ISSUE TITLE
The text (choose file, no file chosen) on this should be translated

### ISSUE THREAD

**Issue by FearsomeRover** [kir-dev/schbody#74]

**Comment by DannySS123** [comment]
@mozsarmate what is this about?

**Comment by Tschonti** [comment]
![image](https://github.com/user-attachments/assets/10315ee1-ecf3-4575-9f66-6bfe90e4d7f1)
in the file upload component

**Comment by DannySS123** [comment]
Since it comes from the browser there is no need for a translation
