### ISSUE TITLE
New Application States

### ISSUE THREAD

**Issue by mozsarmate** [kir-dev/schbody#79]
We have agreed on using a whole new state management system with the customer.
This issue would now involve adding 6 more status-es on the backend, db, and frontend (+frontend design) as well.
I copy the new concept here in hungarian:

Hatalmas új state managment a jelentkezéseknél:
új state: nyomtatásra előkészített
   automatikusan kerüljenek át ide a kiexportált belépősök (tickbox erre a felületen)
új state: legyártott (kinyomtatott?)
   egy gomb megnyomásával a nyomtatásra előkészített-ek átkerülnének ide
régi state: kiosztott
új state: üzemeltetésre vár
   amikor már a listás export megtörtént, ide kerülnek át a kiosztott belépők
új state: érvényes
   ha az üzelemtetés rámondta az áment
új state: lejárt
új state: visszavont

**Comment by mozsarmate** [comment]
dont forget to migrate the db when ready xd

**Comment by Tschonti** [comment]
ez nincs linearon xd

**Comment by mozsarmate** [comment]
hm f

**Comment by mozsarmate** [comment]
Hey @EasySouls , we have agreed on using a whole new state management system with the customer.
This issue would now involve adding 6 more status-es on the backend, db, and frontend (+frontend design) as well.
I copy the new concept here in hungarian:

    Hatalmas új state managment a jelentkezéseknél:
    új state: nyomtatásra előkészített
       automatikusan kerüljenek át ide a kiexportált belépősök (tickbox erre a felületen)
    új state: legyártott (kinyomtatott?)
       egy gomb megnyomásával a nyomtatásra előkészített-ek átkerülnének ide
    régi state: kiosztott
    új state: üzemeltetésre vár
       amikor már a listás export megtörtént, ide kerülnek át a kiosztott belépők
    új state: érvényes
       ha az üzelemtetés rámondta az áment
    új state: lejárt
    új state : visszavont

This issues got a bit more complex, you can try to do it or look for another one.
If you need any help or a nice flow chart of an application's journey (I'll do it next week I hope), don't hesitate to ask me!

**Comment by EasySouls** [comment]
Okay, I will gladly do it, and I will gladly accept the flow chart next week.

**Comment by mozsarmate** [comment]
![image](https://github.com/user-attachments/assets/392ae9b7-e2cf-4063-b9fd-959c83c0c5f3)
Nice! Here you go

**Comment by EasySouls** [comment]
Thanks, I am currently sick, but I'll start working on it as soon as I can.
